Repository paritytech/wiki, pull requests merged in 2018-05, with the labels that each got.

#96 Update Configuring-Parity.md
  Configuring-Parity.md
Labels: F3-annoyance, M2-config

#100 Update CLI Help (Private transactions)
  Configuring-Parity.md
Labels: A0-pleasereview, F5-documentation, M2-config

#101 Rework private transactions wiki page
  Private-Transactions.md
Labels: A0-pleasereview

#102 SecretStore documentation update
  Secret-Store-Configuration.md
  Secret-Store.md
  images/Secret-Store-Glossary-Illustrated.png
Labels: A0-pleasereview

#103 Parity ui flags and multi sig update
  FAQ-User-Interface,-Wallet-and-DApps.md
Labels: M7-ui

#107 Accordion for FAQ pages
  FAQ-Backup,-Restore,-and-Files.md
  FAQ-Basic-Operations,-Configuration,-and-Synchronization.md
  FAQ-Building,-Installation,-and-Testing.md
  FAQ-CLI,-Mining,-and-Networks.md
  FAQ-Customize-Parity-UI.md
  FAQ-Troubleshooting-Yelp!!!!11.md
  FAQ-User-Interface,-Wallet-and-DApps.md
  _includes/head.html
  _layouts/default.html
  public/css/accordion.css
  public/css/parity.css
Labels: F8-enhancement, M3-docs

#110 Fix downloaded->processed
  FAQ-CLI,-Mining,-and-Networks.md
Labels: A0-pleasereview, M4-core

#116 Update parity_netPeers
  JSONRPC-parity-module.md
Labels: F8-enhancement, M6-rpcapi

#114 Update trace_rawTransaction
  JSONRPC-trace-module.md
Labels: M3-docs, M6-rpcapi

#108 Deprecate public node, public wallet, Howto for wallet.parity.io
  Public-Node.md
  Wallet.Parity.Io.md
  images/public-wallet-0.png
  images/public-wallet-1.png
  images/public-wallet-2.png
  images/public-wallet-3.png
  images/public-wallet-4.png
  images/public-wallet-5.png
  images/public-wallet-6.png
  images/public-wallet-7.png
  images/public-wallet-8.png
  images/public-wallet-9.png
  images/public-wallet-a.png
  images/public-wallet-b.png
  images/public-wallet-c.png
  images/public-wallet-d.png
  images/public-wallet-e.png
  images/public-wallet-f.png
  images/public-wallet-g.png
Labels: A0-pleasereview

#118 Add `count` and `after` to trace_filter
  JSONRPC-trace-module.md
Labels: M6-rpcapi

#91 Update link to non deprecated contracts
  Validator-Set.md
Labels: A0-pleasereview

#130 Add security warning to parity and mycrypt mobile signer tuto
  Parity-Signer-Mobile-App-MyCrypto-tutorial.md
  Parity-Signer-Mobile-App-Parity-Wallet-tutorial.md
  Parity-Signer-Mobile-App.md
Labels: F1-security, F8-enhancement

#128 Fix pubsub example
  JSONRPC-Eth-Pub-Sub-Module.md
  JSONRPC-Parity-Pub-Sub-module.md
Labels: A0-pleasereview

#135 Overall rework of the secret store config phrasing
  Secret-Store-Configuration.md
Labels: A8-looksgood, F8-enhancement

#136 Mark external links with an icon
  _includes/Footer.html
  _includes/_Sidebar.md
Labels: A2-insubstantial, F8-enhancement
