Repository paritytech/wiki, pull requests merged in 2018-06, with the labels that each got.

#140 Update Private-development-chain.md
  Private-development-chain.md
Labels: A0-pleasereview

#138 Update Parity module
  JSONRPC-parity-module.md
Labels: A0-pleasereview

#142 Update Chain-specification.md
  Chain-specification.md
Labels: A8-looksgood, M4-core

#137 Transactions queue documentation
  Transactions-Queue.md
  _includes/_Sidebar.md
Labels: A0-pleasereview, M4-core, M6-rpcapi

#143 Clarify how allowedTxTypes is called locally
  Permissioning.md
Labels: A0-pleasereview

#141 Faq revamp
  FAQ-Backup,-Restore,-and-Files.md
  FAQ-Basic-Operations,-Configuration,-and-Synchronization.md
  FAQ-Building,-Installation,-and-Testing.md
  FAQ-CLI,-Mining,-and-Networks.md
  FAQ-Customize-Parity-UI.md
  FAQ-Troubleshooting-Yelp!!!!11.md
  FAQ-User-Interface,-Wallet-and-DApps.md
  FAQ.md
  Setup.md
  _layouts/default.html
  public/css/accordion.css
Labels: A0-pleasereview, F6-refactor, F8-enhancement

#150 Update Remote wallet access with Parity UI
  Wallet-Remote-Access.md
  images/time_is.jpg
Labels: A0-pleasereview

#151 Security best practices in FAQ
  FAQ.md
Labels: A0-pleasereview

#99 Update Known-Issues-Priorities.md
  Known-Issues-Priorities.md
Labels: A0-pleasereview, F9-meta, M3-docs

#158 Update Secret Store config example
  Secret-Store-Configuration.md
Labels: A0-pleasereview

#161 Correct private_contract_key to private_contractKey
  Private-Transactions.md
Labels: A2-insubstantial

#169 Fix secretstore_serversSetHash params
  JSONRPC-secretstore-module.md
Labels: A0-pleasereview
