Repository paritytech/wiki, pull requests merged in 2018-04, with the labels that each got.

#61 Add hardcoded sync header to Chain spec and Light-Client pages
  Chain-specification.md
  FAQ-Basic-Operations,-Configuration,-and-Synchronization.md
  Light-Client.md
Labels: F5-documentation, M2-config, M3-docs

#54 Parity signer page and MyCrypto tutorial
  Parity-Signer-Mobile-App-MyCrypto-tutorial.md
  Parity-Signer-Mobile-App-Parity-Wallet-tutorial.md
  Parity-Signer-Mobile-App.md
  _includes/_Sidebar.md
  images/MyCrypto-Parity-Signer-1.jpg
  images/MyCrypto-Parity-Signer-2.jpg
  images/MyCrypto-Parity-Signer-3.jpg
  images/MyCrypto-Parity-Signer-4.jpg
  images/MyCrypto-Parity-Signer-5.jpg
  images/Parity-Signer-Mobile-App-Watch-Account-with-Parity-Wallet.gif
  images/Parity-Signer-android-0.png
  images/Parity-Signer-android-1.png
  images/Parity-Signer-android-2.png
  images/Parity-Wallet-send-funds-to-account.gif
  images/Parity-wallet-QR-pending-transaction.jpg
Labels: A8-looksgood, F5-documentation, M7-signer

#63 Shorten Sidebar Links
  _includes/_Sidebar.md
Labels: A0-pleasereview, M3-docs

#65 Typo in tutorial
  Parity-Signer-Mobile-App-MyCrypto-tutorial.md
  Parity-Signer-Mobile-App.md
Labels: F3-annoyance, F5-documentation, M3-docs, P2-asap

#68 Document logging abilities
  FAQ-Troubleshooting-Yelp!!!!11.md
Labels: A8-looksgood

#71 Some more wiki fixes & enhancements
  Docker.md
  FAQ-Basic-Operations,-Configuration,-and-Synchronization.md
  FAQ-CLI,-Mining,-and-Networks.md
  Parity-dapp-registry.md
  Permissioning.md
  Pluggable-Consensus.md
  Proof-of-Authority-Chains.md
  Secret-Store.md
  The-Parity-Light-Protocol-(PIP).md
  Tutorial-Part-1.md
  Tutorial-Part-3.md
  Validator-Set.md
  Warp-Sync-Snapshot-Format.md
  Warp-Sync.md
  _includes/head.html
  _layouts/default.html
  public/css/parity.css
Labels: F5-documentation, F8-enhancement, M3-docs

#73 Update RichBlock return struct description on author/miner
  JSONRPC-eth-module.md
Labels: A0-pleasereview, M6-rpcapi

#70 Update chain spec for permissionning
  Chain-specification.md
Labels: A0-pleasereview, F5-documentation, M3-docs

#75 Update getTransactionReceipt
  JSONRPC-eth-module.md
Labels: A0-pleasereview, M3-docs

#79 How to launch parity using Mac OSX terminal
  FAQ-Basic-Operations,-Configuration,-and-Synchronization.md
Labels: F5-documentation, P2-asap

#77 Add parity_chainId documentation
  JSONRPC-parity-module.md
Labels: A0-pleasereview, M6-rpcapi

#85 Add documentation for deterministic stack height metering
  WebAssembly-StackHeight.md
Labels: A8-looksgood, M3-docs, M4-core
