Repository paritytech/wiki, pull requests merged in 2018-08, with the labels that each got.

#215 Fix links
  Chain-specification.md
  Configuring-Parity-Ethereum.md
  FAQ.md
  Light-Client.md
  Secret-Store-Tutorial-2.md
  Secret-Store-Tutorial-3.md
  Secret-Store-Tutorial-4.md
  Transactions-Queue.md
Labels: F3-annoyance

#217 Sidebar enhancements
  _layouts/default.html
  public/css/parity.css
Labels: A0-pleasereview

#212 Add transactionPermissionContractTransition
  Chain-specification.md
Labels: A0-pleasereview

#220 Update Transactions-Queue.md
  Transactions-Queue.md
Labels: A8-looksgood

#216 Private transactions tutorial
  JSONRPC-private-module.md
  Private-Transactions-Tutorial-1.md
  Private-Transactions-Tutorial-2.md
  Private-Transactions-Tutorial-3.md
  Private-Transactions-Tutorial-4.md
  Private-Transactions-Tutorial-Overview.md
  Private-Transactions.md
  _includes/_Sidebar.md
  images/private-tx-remix-screenshot-0.jpg
  images/private-tx-remix-screenshot-1.jpg
  images/private-tx-tutorial-Part-3-overview.jpg
Labels: A0-pleasereview

#223 Update JSONRPC-parity_accounts-module.md
  JSONRPC-parity_accounts-module.md
Labels: A0-pleasereview

#211 Add eip1014 and eip1052 transition config to docs
  Chain-specification.md
Labels: A1-onice, A8-looksgood
