Repository paritytech/wiki, pull requests merged in 2018-03, with the labels that each got.

#28 Fixed Parity-Github-Hint link in the sidebar
  _includes/_Sidebar.md
Labels: A0-pleasereview, A2-insubstantial, F3-annoyance

#33 Clear explanation on how to make changes to the UI
  FAQ-Customize-Parity-UI.md
  FAQ.md
Labels: A8-looksgood, F5-documentation, M7-ui

#37 SecretStore: secretstore_generateDocumentKey
  JSONRPC-secretstore-module.md
Labels: A0-pleasereview, M6-rpcapi

#47 Pre had a double scroll bar even when nothing overflows
  public/css/parity.css
Labels: A8-looksgood

#43 Small wiki updates
  Accounts,-Wallets,-Vaults.md
  Configuring-Parity.md
  Token-Registry.md
  Warp-Sync-Snapshot-Format.md
  images/account-wallet-0.jpg
  images/account-wallet-1.jpg
  images/account-wallet-2.jpg
  images/account-wallet-3.jpg
  images/account-wallet-4.jpg
Labels: M7-ui, M8-dapp, Z0-question

#51 Config clarifications
  Configuring-Parity.md
Labels: A0-pleasereview, M3-docs
