Repository paritytech/wiki, pull requests merged in 2018-07, with the labels that each got.

#145 documenting new fields in eth_getTransactionReceipt
  JSONRPC-eth-module.md
Labels: A1-onice, A8-looksgood

#185 Document parity sub commands
  CLI-Sub-commands.md
  _includes/_Sidebar.md
Labels: A0-pleasereview

#190 Use "Parity Ethereum" and add browser UI move to Parity UI
  FAQ.md
Labels: A0-pleasereview

#178 Secret Store Tutorial
  Secret-Store-Tutorial-1.md
  Secret-Store-Tutorial-2.md
  Secret-Store-Tutorial-3.md
  Secret-Store-Tutorial-4.md
  Secret-Store-Tutorial-overview.md
  _includes/_Sidebar.md
  images/ss-overview-0.jpg
  images/ss-overview-1.jpg
  images/ss-overview-2.jpg
  images/ss-overview-3.jpg
  images/ss-remix-screenshot-0.jpg
Labels: A8-looksgood

#186 Remove links from parent sections
  _includes/_Sidebar.md
Labels: A0-pleasereview, A1-onice, F6-refactor

#180 Update chain-spec and pluggable-consensus
  Chain-specification.md
  Pluggable-Consensus.md
Labels: A0-pleasereview

#202 Replace parity with parity-ethereum
  Bridge.md
  Chain-specification.md
  Configuring-Parity-Ethereum.md
  Docker.md
  FAQ.md
  IPFS.md
  JSONRPC-parity_set-module.md
  Known-Issues-Priorities.md
  Labelling.md
  Light-Client.md
  Parity-Wallet.md
  Release-Notes.md
  Secret-Store-Tutorial-1.md
  Secret-Store.md
  Setup.md
  _includes/_Sidebar.md
Labels: A0-pleasereview

#201 Wiki Product separation
  Parity-Fether-Overview.md
  Public-Node.md
  README.md
  Wallet.Parity.Io.md
  _includes/_Sidebar.md
Labels: A0-pleasereview

#207 Update Setup.md
  Setup.md
Labels: A0-pleasereview

#205 Update Parity UI / Dapps docs + Sidebar dropdowns
  Basic-Usage.md
  Deploying-Dapps-to-Parity-UI.md
  Deploying-Dapps-to-Parity-Wallet.md
  Development-Overview.md
  FAQ.md
  Parity-Fether-Overview.md
  Parity-Github-Hint.md
  Parity-dapp-registry.md
  Parity-name-registry.md
  Register-your-DAPP-for-discovery.md
  Tutorial-Part-1.md
  Tutorial-Part-6.md
  _includes/_Sidebar.md
  _layouts/default.html
  public/css/parity.css
Labels: A9-buythatmanabeer
