Repository paritytech/wiki, pull requests merged in 2019-04, with the labels that each got.

#320 docs: Update Fether FAQ with webcam troubleshooting steps
  Fether-FAQ.md
Labels: A0-pleasereview

#327 docs: Update Fether FAQ with how to add language support and switch languages
  Fether-FAQ.md
Labels: A8-looksgood

#328 [WIP] Running a public node
  Basic-Usage.md
  Configuring-Parity-Ethereum.md
  Getting-Synced.md
Labels: A3-inprogress
